QuanLyBanHang/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QuanLyBanHang.Models;

namespace QuanLyBanHang.Controllers
{
    public class OrdersController : Controller
    {
        private readonly QuanLyBanHangDbContext _context;

        public OrdersController(QuanLyBanHangDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            var userId = "";

            if (userIdClaim != null)
            {
                userId = userIdClaim.Value;
            }

            var quanLyBanHangDbContext = _context.Orders.Where(o => o.UserId == int.Parse(userId));

            return View(await quanLyBanHangDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);

            if (order == null)
            {
                return NotFound();
            }

            order.OrderItems = await _context.OrderItems
                .Include(oi => oi.Product)
                .Where(oi => oi.OrderId == id)
                .ToListAsync();

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,UserId,OrderDate,TotalAmount,ShippingAddress,PaymentMethod,Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,UserId,OrderDate,TotalAmount,ShippingAddress,PaymentMethod,Status")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'QuanLyBanHangDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }
    }
}

QuanLyBanHang/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QuanLyBanHang.Models;

namespace QuanLyBanHang.Controllers
{
    public class UsersController : Controller
    {
        private readonly QuanLyBanHangDbContext _context;

        public UsersController(QuanLyBanHangDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            var userId = "";

            if (userIdClaim != null)
            {
                userId = userIdClaim.Value;
            }

            var user = _context.Users.SingleOrDefault(o => o.UserId == int.Parse(userId));

            if (user == null || _context.Users == null)
            {
                return View();
            }

            return View(user);

        }

        [HttpGet("IsUserNameUnique")]
        public IActionResult IsUserNameUnique(string userName, int userId)
        {
            var isUnique = !_context.Users.Any(u => u.UserName == userName && u.UserId != userId);
            return Json(isUnique);
        }

        [HttpGet("IsPhoneUnique")]
        public IActionResult IsPhoneUnique(string phone, int userId)
        {
            var isUnique = !_context.Users.Any(u => u.Phone == phone && u.UserId != userId);
            return Json(isUnique);
        }

        [HttpGet("IsEmailUnique")]
        public IActionResult IsEmailUnique(string email, int userId)
        {
            var isUnique = !_context.Users.Any(u => u.Email == email && u.UserId != userId);
            return Json(isUnique);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        public IActionResult Login()
        {

            ViewBag.SuccessMessage = TempData["SuccessMessage"] as string;

            return View();
        }
        [HttpPost]
        public IActionResult Login(string userName, string passWord)
        {
            var user = _context.Users.Where(u => u.UserName == userName && u.PassWord == passWord).FirstOrDefault<User>();

            if (user == null || _context.Users == null)
            {
                return View();
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.UserName),
                new Claim(ClaimTypes.Role, user.Role.ToString()),
                new Claim(ClaimTypes.NameIdentifier, user.UserId.ToString()),
            };

            var claimsIdentity = new ClaimsIdentity(
            claims, CookieAuthenticationDefaults.AuthenticationScheme);

            HttpContext.SignInAsync(
            CookieAuthenticationDefaults.AuthenticationScheme,
            new ClaimsPrincipal(claimsIdentity));

            return RedirectToAction("Index", "Home");
        }

        [Route("LogOut")]
        public IActionResult LogOut()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                user.Role = 1;

                _context.Add(user);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Tạo tài khoản thành công!";

                return RedirectToAction(nameof(Login));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name,Email,Address,Phone,UserName,PassWord,Role")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'QuanLyBanHangDbContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.Users?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

QuanLyBanHang/ViewComponents/LoaiSpMenuViewComponent.cs
using QuanLyBanHang.Models;
using QuanLyBanHang.Repository;
using Microsoft.AspNetCore.Mvc;
namespace QuanLyBanHang.ViewComponents
{
    public class LoaiSpMenuViewComponent:ViewComponent
    {
        private readonly ILoaiSpRepository _loaiSp;
        public LoaiSpMenuViewComponent(ILoaiSpRepository loaiSpRepository)
        {
            _loaiSp = loaiSpRepository;

        }
        public IViewComponentResult Invoke()
        {
            var loaisp = _loaiSp.GetAllCategories().OrderBy(x => x.CategoryId);
            return View(loaisp);
        }
    }
}

QuanLyBanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FLEEBOUNCE</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/Layout/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/style.css" type="text/css">

</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row navbar fixed-top navbar-expand-lg navbar-light bg-light" style="box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                <div class="col-lg-3">
                    <div class="header__logo text-center">
                        <a asp-controller="Home" asp-action="Index">
                            <h2>
                                FLEEBOUNCE
                            </h2>
                        </a>
                    </div>
                </div>
                <div class="col-lg-9">
                    <nav class="header__menu" style="text-align: end;">
                        <ul>
                            <li><a style="min-width: 100px; text-align: center;" asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-controller="Carts" asp-action="Index">Giỏ hàng</a>
                                </li>
                            }
                            @if (!(User.Identity.IsAuthenticated))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="Login" asp-controller="Users">Đăng nhập</a>
                                </li>
                            }
                            @if (!(User.Identity.IsAuthenticated))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="Create" asp-controller="Users">Đăng ký</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="Index" asp-controller="Orders">Lịch sử mua hàng</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("0"))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-area="Admin" asp-action="Index" asp-controller="HomeAdmin">Quản lý</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="LogOut" asp-controller="Users">Đăng xuất</a>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" style="margin-top: 96px;" data-setbg="../Layout/img/bannerCart.jpg">
        <div class="container" style="min-height: 550px;">
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container" style="min-height: 265px">
            @RenderBody()
        </div>
    </section>
    <!-- Shoping Cart Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo text-center">
                            <a href="#">
                                <img style="width:90px;" src="~/Layout/img/logo.png" alt="">
                            </a>
                        </div>
                        <ul>
                            <li>Địa chỉ: số 423, đường 19/5</li>
                            <li>Liên hệ: +65 11.188.888</li>
                            <li>Email: xule@gmail.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Liên kết hữu ích</h6>
                        <ul>
                            <li><a href="#">Về chúng tôi</a></li>
                            <li><a href="#">Về cửa hàng của chúng tôi</a></li>
                            <li><a href="#">Mua sắm an toàn</a></li>
                            <li><a href="#">Thông tin giao hàng</a></li>
                            <li><a href="#">Chính sách bảo mật</a></li>
                            <li><a href="#">Bản đồ trang web</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Chúng tôi là ai</a></li>
                            <li><a href="#">Dịch vụ của chúng tôi</a></li>
                            <li><a href="#">Dự án</a></li>
                            <li><a href="#">Liên hệ</a></li>
                            <li><a href="#">Đổi mới</a></li>
                            <li><a href="#">Nhận xét từ khách hàng</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Tham gia với chúng tôi</h6>
                        <p>Liên hệ qua Email</p>
                        <form action="#">
                            <input type="text" placeholder="Nhập Email của bạn">
                            <button type="submit" class="site-btn">Đăng ký</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/Layout/js/jquery-3.3.1.min.js"></script>
    <script src="~/Layout/js/bootstrap.min.js"></script>
    <script src="~/Layout/js/jquery.nice-select.min.js"></script>
    <script src="~/Layout/js/jquery-ui.min.js"></script>
    <script src="~/Layout/js/jquery.slicknav.js"></script>
    <script src="~/Layout/js/mixitup.min.js"></script>
    <script src="~/Layout/js/owl.carousel.min.js"></script>
    <script src="~/Layout/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

QuanLyBanHang/Views/Shared/_LayoutHomepage.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FLEEBOUNCE</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/Layout/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/Layout/css/style.css" type="text/css">
    
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row navbar fixed-top navbar-expand-lg navbar-light bg-light" style="box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                <div class="col-lg-3">
                    <div class="header__logo text-center">
                        <a asp-controller="Home" asp-action="Index">
                            <h2>
                                FLEEBOUNCE
                            </h2>
                        </a>
                    </div>
                </div>
                <div class="col-lg-9">
                    <nav class="header__menu" style="text-align: end;">
                        <ul>
                            <li><a style="min-width: 100px; text-align: center;" asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-controller="Carts" asp-action="Index">Giỏ hàng</a>
                                </li>
                            }
                            @if (!(User.Identity.IsAuthenticated))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="Login" asp-controller="Users">Đăng nhập</a>
                                </li>
                            }
                            @if (!(User.Identity.IsAuthenticated))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="Create" asp-controller="Users">Đăng ký</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="Index" asp-controller="Orders">Lịch sử mua hàng</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="Index" asp-controller="Users">Tài khoản</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("0"))
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-area="Admin" asp-action="Index" asp-controller="HomeAdmin">Quản lý</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a style="min-width: 100px; text-align: center;" asp-action="LogOut" asp-controller="Users">Đăng xuất</a>
                                </li    >
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
    <!-- Hero Section Begin -->
    <section class="hero" style="padding-top: 150px;">
        <div class="container">
            <div class="row" style="min-height: 500px;">
                @await Component.InvokeAsync("LoaiSpMenu")
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form" style="width: 100%;">
                            <form action="#">
                                <input type="text" placeholder="Bạn cần tìm gì ?" />
                                <button style="width: 182px;" type="submit" class="site-btn">Tìm kiếm</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">
                        </div>
                    </div>
                    <div>
                        <img style="width: 100vw;" src="~/Layout/img/banner1.jpg" />
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->
    <!-- Featured Section Begin -->
    <section class="featured spad">
        <div class="container">
            @RenderBody()
        </div>
    </section>
    <!-- Featured Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo text-center">
                            <a href="#">
                                <img style="width:90px;" src="~/Layout/img/logo.png" alt="">
                            </a>
                        </div>
                        <ul>
                            <li>Địa chỉ: số 423, đường 19/5</li>
                            <li>Liên hệ: +65 11.188.888</li>
                            <li>Email: xule@gmail.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Liên kết hữu ích</h6>
                        <ul>
                            <li><a href="#">Về chúng tôi</a></li>
                            <li><a href="#">Về cửa hàng của chúng tôi</a></li>
                            <li><a href="#">Mua sắm an toàn</a></li>
                            <li><a href="#">Thông tin giao hàng</a></li>
                            <li><a href="#">Chính sách bảo mật</a></li>
                            <li><a href="#">Bản đồ trang web</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Chúng tôi là ai</a></li>
                            <li><a href="#">Dịch vụ của chúng tôi</a></li>
                            <li><a href="#">Dự án</a></li>
                            <li><a href="#">Liên hệ</a></li>
                            <li><a href="#">Đổi mới</a></li>
                            <li><a href="#">Nhận xét từ khách hàng</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Tham gia với chúng tôi</h6>
                        <p>Liên hệ qua Email</p>
                        <form action="#">
                            <input type="text" placeholder="Nhập Email của bạn">
                            <button type="submit" class="site-btn">Đăng ký</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/Layout/js/jquery-3.3.1.min.js"></script>
    <script src="~/Layout/js/bootstrap.min.js"></script>
    <script src="~/Layout/js/jquery.nice-select.min.js"></script>
    <script src="~/Layout/js/jquery-ui.min.js"></script>
    <script src="~/Layout/js/jquery.slicknav.js"></script>
    <script src="~/Layout/js/mixitup.min.js"></script>
    <script src="~/Layout/js/owl.carousel.min.js"></script>
    <script src="~/Layout/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>